name: flutter_pay_upi
description: Create app with UPI (Unified Payments Interface)
version: 0.2.1
homepage: https://github.com/abhishekbardolia/flutter_pay_upi.git
issue_tracker: https://github.com/abhishekbardolia/flutter_pay_upi/issues

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - images/
  plugin:
    platforms:
      android:
        package: com.androidsutra.flutter_pay_upi
        pluginClass: FlutterPayUpiPlugin
      ios:
        pluginClass: FlutterPayUpiPlugin
      linux:
        pluginClass: FlutterPayUpiPlugin
      macos:
        pluginClass: FlutterPayUpiPlugin
      windows:
        pluginClass: FlutterPayUpiPluginCApi
      web:
        pluginClass: FlutterPayUpiWeb
        fileName: flutter_pay_upi_web.dart

